MVCTreeViewControl/Models/Node.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace MVCTreeViewControl.Models
{
    public class Node
    {
        public int Id { get; set; }

        public Node Parent { get; set; }

        public string Title { get; set; }

        public string Tooltip { get; set; }

        [DefaultValue(true)]
        public bool Visible { get; set; }

        [DefaultValue(true)]
        public bool IsEditable { get; set; }

        public UrlInfo Url { get; set; }

        public IEnumerable<Node> SubNodes { get; set; }

        public Node()
        {
            Visible = true;
            SubNodes = new List<Node>();
        }
    }
}

MVCTreeViewControl/Models/SampleData.cs
using System.Collections.Generic;
using System.Linq;

namespace MVCTreeViewControl.Models
{
    public static class SampleData
    {
        public static List<Node> Nodes
        {
            get { return GetNodes(); }
        }

        private static IEnumerable<Node> GenerateNodes(int startIndex, int size)
        {
            for (var i = startIndex; i < startIndex + size; i++)
                yield return new Node
                                 {
                                     Id = i,
                                     IsEditable = false,
                                     Title = string.Format("node {0}", i),
                                     Tooltip = string.Format("node tooltip {0}", i),
                                     Url = new UrlInfo { UrlNavigation = "#" },
                                     Visible = true
                                 };
        }

        private static List<Node> GetNodes()
        {
            var parents = GenerateNodes(0, 5).ToList();

            var i = 1;
            foreach (var parent in parents)
            {
                var startIndex = 5 * i++;
                parent.SubNodes =GenerateNodes(startIndex, 5).ToList();
            }

            return parents;
        }
    }
}

MVCTreeViewControl/Models/TreeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCTreeViewControl.Models
{
    public class TreeViewModel
    {
        public IEnumerable<Node> Nodes { get; set; }

        public UrlInfo ExpandUrl { get; set; }

        public string SuccessAlert { get; set; }

        public UrlInfo MainUrl { get; set; }

        public UrlInfo AddUrl { get; set; }

        public UrlInfo EditUrl { get; set; }

        public UrlInfo RemoveUrl { get; set; }

        public string ConfirmMessage { get; set; }

        public string SuccessRemoveMessage { get; set; }

        public TreeViewModel()
        {
            MainUrl = new UrlInfo();
            AddUrl = new UrlInfo();
            EditUrl = new UrlInfo();
            RemoveUrl = new UrlInfo();
            ExpandUrl = new UrlInfo();
        }
    }
}

MVCTreeViewControl/Models/UrlInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCTreeViewControl.Models
{
    public class UrlInfo
    {
        public string Action { get; set; }
        public string Controller { get; set; }
        public string Area { get; set; }
        public object Parammeters { get; set; }
        public string UrlNavigation { get; set; }

        public UrlInfo()
        {
            UrlNavigation = "#";
        }
    }
}

MVCTreeViewControl/Controllers/TreeViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCTreeViewControl.Models;

namespace MVCTreeViewControl.Controllers
{
    public class TreeViewController : Controller
    {
        //
        // GET: /TreeView/
        public ActionResult Index()
        {
            var model = new TreeViewModel();
            model.ExpandUrl.UrlNavigation = "/Treeview/expand";
            model.AddUrl.UrlNavigation = "/Treeview/create";
            model.EditUrl.UrlNavigation = "/Treeview/edit";
            model.Nodes = SampleData.Nodes;
            return View(model);
        }

        [HttpPost]
        public ActionResult Expand(int parentId)
        {
            var json = new JsonResult();
            json.Data = SampleData.Nodes.First(p => p.Id == parentId).SubNodes;
            return Json(json);
        }
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /TreeView/Create

        public ActionResult Create(int? parentId)
        {
            var model = new Node();
            model.Parent = SampleData.Nodes.First(p => p.Id == parentId);

            return View(model);
        }

        //
        // POST: /TreeView/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /TreeView/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /TreeView/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /TreeView/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /TreeView/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MVCTreeViewControl/Views/Shared/_AjaxLayout.cshtml
@RenderSection("Header", false)
@RenderBody()

MVCTreeViewControl/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/css")" rel="stylesheet" type="text/css" />
    <link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Content/themes/base/css")" rel="stylesheet" type="text/css" />
    <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Scripts/js")"></script>
    @RenderSection("Header", false)
</head>
<body>
    @RenderBody()
</body>
</html>

MVCTreeViewControl/Views/TreeView/Create.cshtml
@model MVCTreeViewControl.Models.Node

<script src="@Url.Content("~/Scripts/jquery-1.6.2.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>

@using (Html.BeginForm("Create", "TreeView", FormMethod.Post, new { @class = "arkad-form" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Node</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Tooltip)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Tooltip)
            @Html.ValidationMessageFor(model => model.Tooltip)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Visible)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Visible)
            @Html.ValidationMessageFor(model => model.Visible)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsEditable)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsEditable)
            @Html.ValidationMessageFor(model => model.IsEditable)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVCTreeViewControl/Views/TreeView/Index.cshtml
@using MVCTreeViewControl.Helper
@model MVCTreeViewControl.Models.TreeViewModel
@section Header
{
    <link href="@Url.Content("../../../../Content/Confirm.css")" rel="stylesheet" type="text/css"  media="screen" />
    <link rel="stylesheet" type="text/css" href="../../Content/treeview.css" />
    <script type="text/javascript" src="@Url.Content("../../../../Scripts/jquery.validate.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("../../../../Scripts/jquery.simplemodal.1.4.1.min.js")" ></script>
    <script type="text/javascript" src="@Url.Content("../../../../Scripts/jquery.validate.unobtrusive.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("../../../../Scripts/jquery.simplemodal.1.4.1.min.js")" ></script>
    <script type="text/javascript" src="@Url.Content("../../../../Scripts/arkad.js")" ></script>
    <script type="text/javascript" src="@Url.Content("../../../../Scripts/arkad.treeview.js")" ></script>
    <script type="text/javascript">
        arkad.ui.treeview.expandUrl = "@Model.ExpandUrl.UrlNavigation";
        arkad.ui.treeview.successEditAlert = "@Model.SuccessAlert";
        arkad.ui.treeview.successAddAlert = "@Model.SuccessAlert";
        arkad.ui.treeview.successRemoveAlert = "@Model.SuccessRemoveMessage";
        arkad.ui.treeview.mainPageUrl = "@Model.MainUrl.UrlNavigation";
        arkad.ui.treeview.addItemPopupUrl = "@Model.AddUrl.UrlNavigation";
        arkad.ui.treeview.editItemPopupUrl = "@Model.EditUrl.UrlNavigation";
        arkad.ui.treeview.removeItemPopupUrl = "@Model.RemoveUrl.UrlNavigation";
        arkad.ui.treeview.successRemoveAlert = "@Model.SuccessRemoveMessage";
    </script>
}
@Html.TreeView(m => m.AddRange(Model.Nodes.ToList()))
<script type="text/javascript">
    function add(parentId) {
        arkad.ui.treeview.add(parentId);
    };
    function edit(id) {
        arkad.ui.treeview.edit(id);
    };
    function remove(id) {
        arkad.ui.treeview.remove(id);
    };
    function expand(id) {
        arkad.ui.treeview.expand(id);
    };
    function onMouseOutFromToolbar(id) {
        arkad.ui.treeview.onMouseOutFromToolbar(id);
    };
    function onClickNode(id) {
        arkad.ui.treeview.onClickNode(id);
    };
</script>